"""Groundedness judge — the reusable primitive, in core/ so both the eval harness and the live
Phase 12 reviewer can call it.

A judge is one extra LLM call that scores an output against a rubric and returns a structured
`JudgeVerdict` (via the same `complete_structured` / `messages.parse` path the rest of core/ uses).
The judge model MUST differ from the judged model: the memo is generated by Sonnet, so the judge is
Opus (config.judge_model / reviewer_model) — don't let a model grade its own blind spots
(phase-6 IMPLEMENTATION §6). That discipline holds whether this runs offline (eval) or live (the
Phase 12 reviewer): Opus reviewer != Sonnet analyst.

Groundedness is the legal-integrity metric: the judge sees an obligation claim plus the statute
text it cites, and decides whether the claim is supported by THAT text — the check that catches a
plausible-sounding but hallucinated obligation, the worst failure for a compliance tool.

Lifted from eval/judge.py in Phase 12 (the "build once, deploy two ways" precedent, same as Phase 7
moving grounding.py into core/): eval/judge.py now imports these back up and keeps only the aggregator.
"""

from typing import Literal

from pydantic import BaseModel

from patchwork_assurance.core.contracts import Msg

JUDGE_SYSTEM = (
    "You are a careful legal-evaluation judge. You are given an OBLIGATION CLAIM written by a "
    "compliance tool and the STATUTE TEXT it cites. Decide whether the claim is supported by THAT "
    "text only — not by your own legal knowledge. Return 'yes' if the claim is fully supported by "
    "the text, 'partial' if it is only partly supported or overstates what the text says, and 'no' "
    "if the text does not support the claim (a hallucinated or unsupported obligation). List the "
    "specific unsupported pieces in unsupported_claims. Be strict but fair: hedged, accurate "
    "summaries of the text are 'yes'."
)


class JudgeVerdict(BaseModel):
    grounded: Literal["yes", "partial", "no"]
    reason: str
    unsupported_claims: list[str] = []


def _grounding_user(claim: str, statute_text: str) -> str:
    return f"## OBLIGATION CLAIM\n{claim}\n\n## CITED STATUTE TEXT\n{statute_text}\n"


def judge_groundedness(claim: str, statute_text: str, llm) -> JudgeVerdict:
    """One judged call: is `claim` supported by `statute_text`? `llm` is any LLMClient (Opus in
    production; a stub returning a fixed verdict in tests)."""
    return llm.complete_structured(
        JUDGE_SYSTEM,
        [Msg(role="user", content=_grounding_user(claim, statute_text))],
        JudgeVerdict,
    )
